### ISSUE TITLE
Sort of a bug with urlencode - please double check...

### ISSUE THREAD

**Issue by egandro** [swaggest/swgui#21]
I think i found sort of a bug with urlencoding of slashes.

Here what's going on:

I have an endpoint `/api/hello/{name}`

In the UI I enter "World" for Name. 

This is now the Request URL `http://localhost:8080/api/hello/World`

In the UI I enter "World/of/bugs" for `{name}`. 

This is now the Request URL `http://localhost:8080/api/hello/World%2Fof%2Fbugs`

However - this is wrong. The webserver will resolve this to this:

`[GIN] 2021/04/04 - 23:49:31 | 404 |       2.853µs |      172.17.0.1 | GET      "/api/hello/World/of/bugs"`

Which is wrong :) That is simply a different endpoint. It is  `/api/hello/{a}/{b}/{c}` and not `/api/hello/{name}`.

Slashes (maybe other stuff?) needs to be double encoded like this. Not just a singletime urlencoded :)

`http://localhost:8080/api/hello/World%252Fof%252Fbugs`

This is how it will arrive on the webserver:

`[GIN] 2021/04/04 - 23:52:28 | 200 |    1.221707ms |      172.17.0.1 | GET      "/api/hello/World%2Fof%2Fbugs"`

Which is now the correct data in the application:

```
{
  "message": "Hello, World/of/bugs!"
}
```

Please double check...

**Comment by egandro** [comment]
Edit: Please double check if this is a problem.

It might be an issue with my API Gateway and not related at all to swaggest/ swgui

**Comment by vearutop** [comment]
This case can be easily tested with https://github.com/swaggest/rest/tree/v0.2.1/_examples/basic that provides almost similar API.

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/1381436/113773224-0a29e000-9726-11eb-8cb2-591a39e6cd0d.png">

It works as expected, with path item properly escaped. 

If you have the issue of unexpected path decoding, it is likely happening somewhere in transit, not caused by Swagger UI itself.

**Comment by egandro** [comment]
Dear @vearutop,

I think the bug is in krakend: https://github.com/devopsfaith/krakend-ce/issues/290

I am closing this bug here.

**Comment by egandro** [comment]
Dear @vearutop 

I fixed my upstream bug :) https://github.com/devopsfaith/krakend-ce/pull/291/files

**Comment by vearutop** [comment]
Great, congrats on finding and fixing the root cause issue!
